spring:
  application:
    name: spring-cloud-user-1
  datasource:
    url: jdbc:mysql://9.134.73.179:3306/fssl_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: fssl
    password: Fssl
    
server:
  port: 8333

mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  type-aliases-package: com.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka