server:
  port: 9006
spring:
  application:
    name: gateway-zuul-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

zuul:
  host:
    connect-timeout-millis: 12000
    socket-timeout-millis: 12000
  routes:
    api-a:
      path: /api-a/**
      service-id: spring-cloud-user-1
      sensitive-headers:
    api-b:
      path: /api-b/**
      service-id: spring-cloud-shopping

   
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000

                  
ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 12000